### ISSUE TITLE
Ceph nodes upgrade to Rocky9

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#140]
Upgrade remaining Ceph nodes to rocky9

- [x] sv-hdd-12-0
- [x] sv-hdd-12-1
- [x] sv-hdd-12-2
- [x] sv-hdd-12-3
- [x] sv-hdd-12-4
- [x] sv-hdd-12-5
- [x] sv-hdd-12-6
- [x] sv-hdd-12-7
- [x] sv-hdd-12-8
- [x] sv-hdd-12-9
- [x] sv-hdd-12-10
- [x] sv-hdd-12-11
- [x] sv-hdd-12-12
- [x] sv-hdd-12-13

- [x] sv-ssd-0-0
- [x] sv-ssd-0-1
- [x] sv-ssd-0-2
- [x] sv-ssd-0-3
- [x] sv-ssd-0-4
- [x] sv-ssd-0-5
- [x] sv-ssd-0-6
- [x] sv-ssd-0-7

**Comment by GregBlow** [comment]
> Piotr Parczewski
>   [4 hours ago](https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1701424786767209?thread_ts=1701250697.198579&cid=C01Q56Q78LT)
> sv-hdd-12-6, sv-hdd-12-13 & sv-ssd-0-7 are on Rocky

**Comment by GregBlow** [comment]
```
[ceph: root@sv-hdd-12-0 /]# ceph orch host maintenance enter sv-hdd-12-11
Daemons for Ceph cluster 84c543e0-58d2-11ec-be7d-f40343cb8bc0 stopped on host sv-hdd-12-11. Host sv-hdd-12-11 moved to maintenance mode
```

**Comment by GregBlow** [comment]
```
[ceph: root@sv-hdd-12-0 /]# ceph orch ps sv-hdd-12-11
NAME                HOST          PORTS  STATUS   REFRESHED  AGE  MEM USE  MEM LIM  VERSION  IMAGE ID      CONTAINER ID
crash.sv-hdd-12-11  sv-hdd-12-11         stopped     7m ago   6M    7688k        -  17.2.6   c9a1062f7289  ac3d0d66a0a4
osd.395             sv-hdd-12-11         stopped     7m ago   6M    3957M    6930M  17.2.6   c9a1062f7289  c6fd12653ce4
osd.402             sv-hdd-12-11         stopped     7m ago   6M    3289M    6930M  17.2.6   c9a1062f7289  17bc13f3bc04
osd.404             sv-hdd-12-11         stopped     7m ago   6M    8177M    6930M  17.2.6   c9a1062f7289  afd160436261
osd.411             sv-hdd-12-11         stopped     7m ago   6M    9507M    6930M  17.2.6   c9a1062f7289  8fa026b7ed1d
osd.418             sv-hdd-12-11         stopped     7m ago   6M    9491M    6930M  17.2.6   c9a1062f7289  e7e735fb4d5d
osd.425             sv-hdd-12-11         stopped     7m ago   6M    8802M    6930M  17.2.6   c9a1062f7289  9a544475ab6f
osd.433             sv-hdd-12-11         stopped     7m ago   6M    8420M    6930M  17.2.6   c9a1062f7289  fe6bca7aff37
osd.439             sv-hdd-12-11         stopped     7m ago   6M    7584M    6930M  17.2.6   c9a1062f7289  7c8034ff3377
osd.446             sv-hdd-12-11         stopped     7m ago   6M    8113M    6930M  17.2.6   c9a1062f7289  749c1da849df
osd.453             sv-hdd-12-11         stopped     7m ago   6M    7818M    6930M  17.2.6   c9a1062f7289  f422d0329429
osd.460             sv-hdd-12-11         stopped     7m ago   6M    8902M    6930M  17.2.6   c9a1062f7289  62c7ed3c1257
osd.467             sv-hdd-12-11         stopped     7m ago   6M    7798M    6930M  17.2.6   c9a1062f7289  c0c5a52c81af
osd.474             sv-hdd-12-11         stopped     7m ago   6M    7674M    6930M  17.2.6   c9a1062f7289  4fd1845b25df
osd.481             sv-hdd-12-11         stopped     7m ago   6M    9336M    6930M  17.2.6   c9a1062f7289  acea77d415d4
osd.488             sv-hdd-12-11         stopped     7m ago   6M    7796M    6930M  17.2.6   c9a1062f7289  b48d2dbc5703
osd.495             sv-hdd-12-11         stopped     7m ago   6M    7763M    6930M  17.2.6   c9a1062f7289  db673a4cf8bc
osd.502             sv-hdd-12-11         stopped     7m ago   6M    9270M    6930M  17.2.6   c9a1062f7289  466dad111be9
osd.509             sv-hdd-12-11         stopped     7m ago   6M    9073M    6930M  17.2.6   c9a1062f7289  65ce3bacf8f8
osd.516             sv-hdd-12-11         stopped     7m ago   6M    7950M    6930M  17.2.6   c9a1062f7289  5dd5a1946dea
osd.523             sv-hdd-12-11         stopped     7m ago   6M    7840M    6930M  17.2.6   c9a1062f7289  e8a58022ff64
osd.530             sv-hdd-12-11         stopped     7m ago   6M    8214M    6930M  17.2.6   c9a1062f7289  05274a96826f
osd.537             sv-hdd-12-11         stopped     7m ago   6M    8488M    6930M  17.2.6   c9a1062f7289  773aad43834e
osd.544             sv-hdd-12-11         stopped     7m ago   6M    9192M    6930M  17.2.6   c9a1062f7289  8309bbdd9458
osd.551             sv-hdd-12-11         stopped     7m ago   6M    7545M    6930M  17.2.6   c9a1062f7289  39dd5c0a99a9
osd.558             sv-hdd-12-11         stopped     7m ago   6M    7931M    6930M  17.2.6   c9a1062f7289  2297618f114c
osd.565             sv-hdd-12-11         stopped     7m ago   6M    7756M    6930M  17.2.6   c9a1062f7289  2b014e87ad40
```

**Comment by GregBlow** [comment]
```
(kayobe) [stack@sv-admin-0 kayobe]$ kayobe playbook run $KAYOBE_CONFIG_PATH/ansible/cephadm-deploy.yml
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details
ERROR! the role 'stackhpc.cephadm.cephadm' was not found in /home/stack/kayobe/src/kayobe-config/etc/kayobe/ansible/roles:/home/stack/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/stack/kayobe/src/kayobe-config/etc/kayobe/ansible

The error appears to be in '/home/stack/kayobe/src/kayobe-config/etc/kayobe/ansible/cephadm-deploy.yml': line 11, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - import_role:
        name: stackhpc.cephadm.cephadm
              ^ here
Kayobe playbook(s) /home/stack/kayobe/src/kayobe-config/etc/kayobe/ansible/cephadm-deploy.yml exited 1
(kayobe) [stack@sv-admin-0 kayobe]$ env | grep KAYOBE
KAYOBE_VAULT_PASSWORD=iQgLZFY8gt0BmWHlMqK4XWAl
KAYOBE_CONFIG_PATH=/home/stack/kayobe/src/kayobe-config/etc/kayobe
KAYOBE_ENVIRONMENT=somerville
```
Got around by manually adding ceph key to authorised keys.

**Comment by GregBlow** [comment]
Every 2.0s: ceph orch ps sv-hdd-12-11                                                                                                                  sv-hdd-12-0: Fri Dec  1 17:09:06 2023

NAME                HOST          PORTS  STATUS    REFRESHED  AGE  MEM USE  MEM LIM  VERSION    IMAGE ID
crash.sv-hdd-12-11  sv-hdd-12-11         starting          -    -        -        -  <unknown>  <unknown>
osd.395             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.402             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.404             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.411             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.418             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.425             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.433             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.439             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.446             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.453             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.460             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.467             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.474             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.481             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.488             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>
osd.495             sv-hdd-12-11         starting          -    -        -    4096M  <unknown>  <unknown>

**Comment by GregBlow** [comment]
```
Every 2.0s: ceph orch ps sv-hdd-12-11                                                                                                                  sv-hdd-12-0: Fri Dec  1 17:15:28 2023

NAME                HOST          PORTS  STATUS        REFRESHED  AGE  MEM USE  MEM LIM  VERSION  IMAGE ID      CONTAINER ID
crash.sv-hdd-12-11  sv-hdd-12-11         running (7m)    28s ago   7m    7100k        -  17.2.6   c9a1062f7289  7f2dca17489d
osd.395             sv-hdd-12-11         running (6m)    28s ago   6m    1111M    6930M  17.2.6   c9a1062f7289  98859604d38d
osd.402             sv-hdd-12-11         running (6m)    28s ago   6m    1234M    6930M  17.2.6   c9a1062f7289  1a5db98fee81
osd.404             sv-hdd-12-11         running (6m)    28s ago   6m    4202M    6930M  17.2.6   c9a1062f7289  1ef7c7e50faa
osd.411             sv-hdd-12-11         running (6m)    28s ago   6m    3026M    6930M  17.2.6   c9a1062f7289  2d65335d2a88
osd.418             sv-hdd-12-11         running (6m)    28s ago   6m    3581M    6930M  17.2.6   c9a1062f7289  dccb2df3fe4e
osd.425             sv-hdd-12-11         running (6m)    28s ago   6m    1762M    6930M  17.2.6   c9a1062f7289  80584a6c34a5
osd.433             sv-hdd-12-11         running (6m)    28s ago   6m    1770M    6930M  17.2.6   c9a1062f7289  5a3fd893b9c0
osd.439             sv-hdd-12-11         running (6m)    28s ago   6m    3533M    6930M  17.2.6   c9a1062f7289  3ada6891b4f1
osd.446             sv-hdd-12-11         running (6m)    28s ago   6m    4215M    6930M  17.2.6   c9a1062f7289  363d4516dbdd
osd.453             sv-hdd-12-11         running (6m)    28s ago   6m    2163M    6930M  17.2.6   c9a1062f7289  742c39508f1b
osd.460             sv-hdd-12-11         running (6m)    28s ago   6m    2159M    6930M  17.2.6   c9a1062f7289  e350df89156e
osd.467             sv-hdd-12-11         running (6m)    28s ago   6m    1894M    6930M  17.2.6   c9a1062f7289  fe1ba41ca853
osd.474             sv-hdd-12-11         running (6m)    28s ago   6m    2657M    6930M  17.2.6   c9a1062f7289  c95a10d3bead
osd.481             sv-hdd-12-11         running (6m)    28s ago   6m    2546M    6930M  17.2.6   c9a1062f7289  d8ab98920397
osd.488             sv-hdd-12-11         running (6m)    28s ago   6m    2651M    6930M  17.2.6   c9a1062f7289  968750fc0079
osd.495             sv-hdd-12-11         running (6m)    28s ago   6m    2144M    6930M  17.2.6   c9a1062f7289  14de1c205aa6
osd.502             sv-hdd-12-11         running (6m)    28s ago   6m    4937M    6930M  17.2.6   c9a1062f7289  c9ce59088a00
osd.509             sv-hdd-12-11         running (6m)    28s ago   6m    3028M    6930M  17.2.6   c9a1062f7289  a68ad31b3d79
osd.516             sv-hdd-12-11         running (6m)    28s ago   6m    2732M    6930M  17.2.6   c9a1062f7289  062a1edfc6c5
osd.523             sv-hdd-12-11         running (6m)    28s ago   6m    2165M    6930M  17.2.6   c9a1062f7289  b7fced1e821b
osd.530             sv-hdd-12-11         running (6m)    28s ago   6m    3600M    6930M  17.2.6   c9a1062f7289  bd678db3a2c6
osd.537             sv-hdd-12-11         running (6m)    28s ago   6m    1807M    6930M  17.2.6   c9a1062f7289  f1b1e664e8a7
osd.544             sv-hdd-12-11         running (6m)    28s ago   6m    3110M    6930M  17.2.6   c9a1062f7289  85183e7c7c9f
osd.551             sv-hdd-12-11         running (6m)    28s ago   6m    2623M    6930M  17.2.6   c9a1062f7289  8aee2c59d6c4
osd.558             sv-hdd-12-11         running (6m)    28s ago   6m    3388M    6930M  17.2.6   c9a1062f7289  e09107df7473
osd.565             sv-hdd-12-11         running (6m)    28s ago   6m    2790M    6930M  17.2.6   c9a1062f7289  26b700f8e4e4
```

**Comment by GregBlow** [comment]
```
[ceph: root@sv-hdd-12-0 /]# ceph -w
  cluster:
    id:     84c543e0-58d2-11ec-be7d-f40343cb8bc0
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum sv-hdd-12-1,sv-hdd-12-0,sv-hdd-12-2 (age 3d)
    mgr: sv-hdd-12-1.zjxcoa(active, since 20h), standbys: sv-hdd-12-0.blmxth, sv-hdd-12-2.bdmqkd
    mds: 4/4 daemons up, 4 standby
    osd: 572 osds: 572 up (since 6m), 572 in (since 6M)
    rgw: 12 daemons active (6 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   14 pools, 12657 pgs
    objects: 1.08G objects, 601 TiB
    usage:   1.8 PiB used, 2.0 PiB / 3.8 PiB avail
    pgs:     12602 active+clean
             54    active+clean+scrubbing+deep
             1     active+clean+scrubbing

  io:
    client:   13 KiB/s rd, 9.0 MiB/s wr, 26 op/s rd, 329 op/s wr
    ```

**Comment by GregBlow** [comment]
```
[ceph: root@sv-hdd-12-0 /]# ceph -s
  cluster:
    id:     84c543e0-58d2-11ec-be7d-f40343cb8bc0
    health: HEALTH_OK

  services:
    mon: 3 daemons, quorum sv-hdd-12-1,sv-hdd-12-0,sv-hdd-12-2 (age 3d)
    mgr: sv-hdd-12-1.zjxcoa(active, since 20h), standbys: sv-hdd-12-0.blmxth, sv-hdd-12-2.bdmqkd
    mds: 4/4 daemons up, 4 standby
    osd: 572 osds: 572 up (since 6m), 572 in (since 6M)
    rgw: 12 daemons active (6 hosts, 1 zones)

  data:
    volumes: 1/1 healthy
    pools:   14 pools, 12657 pgs
    objects: 1.08G objects, 601 TiB
    usage:   1.8 PiB used, 2.0 PiB / 3.8 PiB avail
    pgs:     12602 active+clean
             53    active+clean+scrubbing+deep
             2     active+clean+scrubbing

  io:
    client:   13 KiB/s rd, 10 MiB/s wr, 22 op/s rd, 373 op/s wr
    ```
