### ISSUE TITLE
Add new Lasair flavours for new hypervisors

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#161]
Diff Mar24 & Oct24 to derive changes

https://docs.google.com/spreadsheets/d/1HZw1lzirKBM8TRc4qYm1eAiyHNOGrNHr_eHMmA8WF48/edit#gid=1587892404

**Comment by gpfrancis** [comment]
Assuming that ephemeral storage comes in integer multiples of a ~4TB drive my suggestion would be two flavours: a large (8 core, 32G) with one disk and an x-large (16 core, 64G) with two. We might come back and ask for something more carefully tailored later, but those are my best guess as to what is appropriate.

**Comment by GregBlow** [comment]
first draft written and ready for testing on return of system and addition of appropriate hypervisors

**Comment by GregBlow** [comment]
https://git.ecdf.ed.ac.uk/lsstuk-somerville/openstack-config/-/merge_requests/103

**Comment by astrodb** [comment]
HVs are deployed. New method of creating 'nvme' volumes is available. Tests are underway.

**Comment by GregBlow** [comment]
Still pending configuration of hypervisors.

**Comment by astrodb** [comment]
Status?

**Comment by GregBlow** [comment]
we have two flavours configured as such:

```

somerville_flavor_lasair_large_eph_ssd:
  name: lasair-large-eph-ssd
  ram: 32768
  vcpus: 8
  disk: 0
  ephemeral: 3840

somerville_flavor_lasair_xlarge_eph_ssd:
  name: lasair-xlarge-eph-ssd
  ram: 65536
  vcpus: 16
  disk: 0
  ephemeral: 7680

```

The original google doc is no long available. I am looking to apply these now, but the ansible tooling requires repair.
