### ISSUE TITLE
Reconcile magnum-mgmt quota discrepancy

### ISSUE THREAD

**Issue by GregBlow** [lsst-uk/somerville-operations#210]
ansible error on unrelated task highlighted discrepancy between config and actual.

```
(openstack-config)  2 stack@sv-admin-0:~/gblow/oct2024/src/openstack-config (somerville/2023.1)$ openstack quota show magnum-mgmt
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field                 | Value
    |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| backup-gigabytes      | -1
    |
| backups               | -1
    |
| cores                 | 30
    |
| fixed-ips             | -1
    |
| floating-ips          | 50
    |
| gigabytes             | 900
    |
| gigabytes_ceph-hdd    | -1
    |
| gigabytes_ceph-ssd    | -1
    |
| gigabytes_multiattach | -1
    |
| gigabytes_nvme        | -1
    |
| groups                | 10
    |
| injected-file-size    | -1
    |
| injected-files        | -1
    |
| injected-path-size    | 255
    |
| instances             | 15
    |
| key-pairs             | -1
    |
| location              | Munch({'cloud': '', 'region_name': 'RegionOne', 'zone': None, 'project': Munch({'id': 'ff3e2de6a0b844d581bcd4335c18d2a4', 'name': 'admin', 'domain_id': None, 'domain_name': 'Default'})}) |
| networks              | 100
    |
| per-volume-gigabytes  | -1
    |
| ports                 | 500
    |
| project               | ba80922bc87c4d59a409c1ad2ce1d003
    |
| project_name          | magnum-mgmt
    |
| properties            | 128
    |
| ram                   | 131072
    |
| rbac_policies         | 10
    |
| routers               | 10
    |
| secgroup-rules        | 100
    |
| secgroups             | 10
    |
| server-group-members  | 10
    |
| server-groups         | 10
    |
| snapshots             | 100
    |
| snapshots_ceph-hdd    | -1
    |
| snapshots_ceph-ssd    | -1
    |
| snapshots_multiattach | -1
    |
| snapshots_nvme        | -1
    |
| subnet_pools          | -1
    |
| subnets               | 100
    |
| volumes               | 30
    |
| volumes_ceph-hdd      | -1
    |
| volumes_ceph-ssd      | -1
    |
| volumes_multiattach   | -1
    |
| volumes_nvme          | -1
    |
+-----------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

```
somerville_magnum_mgmt_quota:
  backup_gigabytes: -1
  backups: -1
  cores: 20
  fixed-ips: -1
  floating-ips: 5
  gigabytes: 900
  injected_file_size: -1
  injected_files: -1
  instances: 10
  key_pairs: -1
  per_volume_gigabytes: -1
  ram: 65536
  secgroup_rules: -1
  secgroups: -1
  snapshots: 100
  volumes: 20

```
