### ISSUE TITLE
Heat stack create/update issue

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/somerville-operations#66]
Attempting to create or update a heat stack for Lasair usually fails with an error message similar to this:
```
"Failure in updating stack: Resource CREATE failed: BadRequest: resources.kafka_pub.resources.srv: Block Device Mapping is Invalid: failed to get volume 8b4a8bb3-ab59-439b-acf7-9f5199f4ed2a. (HTTP 400) (Request-ID: req-340a84c6-10a8-44eb-8f5d-52695391865a)"
```

Creating an empty stack with no instances appears to work fine.

Updating the stack to add instances appears to work if the instances spawn quickly, but fail if they take a long time to spawn (even though they do ultimately do so).

Adding instances one at a time to an empty stack and finding that ~25% of the time the instance takes about 1min to spawn and the addition works; the rest of the time the instances takes >5 min to spawn and the addition fails. Failed additions can be rolled back OK and retried. There does not appear to be any correlation between instance type or group and either how long it takes to spawn or whether the update works.

1. Why is it taking so long to spawn instances most of the time?
2. But not always?
3. This feels like a ~5min timeout in heat. Is it?

**Comment by astrodb** [comment]
Troubleshooting chat from Slack:

The log of what we tried is in a thread in #rubin-science-platform in the LSST:UK slack.
11:31
Quick summary: as of early autumn, Magnum appeared to be working. Stelios and I both had clusters deployed in the RSP project using a copy of the template that we got from Piotr.
11:32
In December, things did not seem to be working. I tried resizing my cluster to add more workers and it ended up in state "UPDATE_FAILED"
11:32
I tried to delete and recreate the cluster and the create failed
11:33
Eventually 
@Mark Holliman
 and I were able to find time to work through an attempted deployment together just before the holidays
11:34
We verified that using the template that had previously worked now failed with what looked like networking related errors
11:37
We found that adding the parameter 'fixed_subnet_cidr': '10.71.0.0/24' to the template seemed to help. Perhaps there is a conflict if multiple clusters all try to use the default 10.0.0.0/24 subnet. Although why this should have worked previously and then stopped I don't know.
11:37
However, the deployment is still failing.
11:38
It is also taking a long time to get to the failed state which makes debugging slow work.

**Comment by astrodb** [comment]
And to reproduce:

The two cluster templates I was using were gf-test e5024c2a-2f1c-4f7c-9409-a1e132038c45  and gf-test-2 e8cbf656-4505-4f3b-afbf-f8c2a1ea5452 both in the RSP project.
12:03
The Heat create/update issue relates to the Lasair project. I was using this template: https://github.com/lsst-uk/lasair-deploy/blob/develop/heat_template.yaml although I would suggest using something smaller and simpler for debugging.

**Comment by gpfrancis** [comment]
Comment from the user liason meeting: the Heat and Magnum issues may well have a common cause so it may make sense technically to work on the Heat issue first, but from a user POV getting Magnum working is actually slightly more urgent.

**Comment by GregBlow** [comment]
[server_with_volume.yaml](https://github.com/lsst-uk/lasair-deploy/blob/develop/server_with_volume.yaml)

**Comment by GregBlow** [comment]
[lasair_problem_heat.txt](https://github.com/lsst-uk/somerville-operations/files/10548706/lasair_problem_heat.txt)

**Comment by GregBlow** [comment]
errors appear to be local to Kafka group resource group 

```
kafka_group:
    properties:
      count:
        get_param: n_kafka
      resource_def:
        properties:
          flavor:
            get_param: flavor_kafka
          image_id:
            get_param: image_id
          key_name:
            get_param: key_name
          net:
            get_param: net
          server_group:
            get_resource: kafka_server_group
          server_name:
            list_join:
            - '-'
            - - get_param: OS::stack_name
              - kafka
              - '%index%'
          volume_size:
            get_param: volume_small
        type: https://raw.githubusercontent.com/lsst-uk/lasair-deploy/develop/server_with_volume.yaml
    type: OS::Heat::ResourceGroup
```

**Comment by GregBlow** [comment]
issue is replicated when no optional groups (create_db, create_web, etc) are selected.

**Comment by GregBlow** [comment]
notable differences with other resource group only that extra_volume_size and extra_volume_type properties not present, and that flavor is different. Suggests problem is with flavor.

**Comment by GregBlow** [comment]
G Francis
  [5:27 PM](https://ifaedinburghs-ofn4738.slack.com/archives/C03SK93N84C/p1675186064118329)
What I was seeing in December was that adding instances usually, but not always, took a long time and failed. No difference between different types.
[5:28](https://ifaedinburghs-ofn4738.slack.com/archives/C03SK93N84C/p1675186102010039)
What I'm seeing now is that any number of kafka instances fails, and in a different way. Some other combinations work. So something has changed at some point.
[5:30](https://ifaedinburghs-ofn4738.slack.com/archives/C03SK93N84C/p1675186231889389)
Just added three ingest instances and that works too.

**Comment by GregBlow** [comment]
<html><body>


Stack Resource | Resource | Time Since Event | Status | Status Reason
-- | -- | -- | -- | --
issue-66-test-4 | 0fb3dcdd-6db6-4200-b511-5df63601906c | 14 hours, 12 minutes | Create Failed | Resource CREATE failed: Unauthorized:  resources.sherlock_group.resources[0].resources.extra_vol_attachment:  The request you have made requires authentication. (HTTP 401)
sherlock_group | 6f07154d-4b07-43b9-a2f9-482ddbdb8d2c | 14 hours, 12 minutes | Create Failed | Unauthorized:  resources.sherlock_group.resources[0].resources.extra_vol_attachment:  The request you have made requires authentication. (HTTP 401)
issue-66-test-4 | 0fb3dcdd-6db6-4200-b511-5df63601906c | 14 hours, 12 minutes | Create Failed | Resource CREATE failed: Unauthorized:  resources.cassandra_group.resources[0].resources.extra_vol_attachment:  The request you have made requires authentication. (HTTP 401)
cassandra_group | e5cdfb6b-118b-416d-a06c-fe8042463134 | 14 hours, 12 minutes | Create Failed | Unauthorized:  resources.cassandra_group.resources[0].resources.extra_vol_attachment:  The request you have made requires authentication. (HTTP 401)


</body>
</html>Stack Resource
	Resource
	Time Since Event
	Status
	Status Reason
issue-66-test-4 	0fb3dcdd-6db6-4200-b511-5df63601906c 	14 hours, 12 minutes 	Create Failed 	Resource CREATE failed: Unauthorized: resources.[sherlock_group](https://somerville.ed.ac.uk/project/stacks/stack/0fb3dcdd-6db6-4200-b511-5df63601906c/sherlock_group/).resources[0].resources.extra_vol_attachment: The request you have made requires authentication. (HTTP 401)
sherlock_group	6f07154d-4b07-43b9-a2f9-482ddbdb8d2c 	14 hours, 12 minutes 	Create Failed 	Unauthorized: resources.sherlock_group.resources[0].resources.extra_vol_attachment: The request you have made requires authentication. (HTTP 401)
issue-66-test-4 	0fb3dcdd-6db6-4200-b511-5df63601906c 	14 hours, 12 minutes 	Create Failed 	Resource CREATE failed: Unauthorized: resources.[cassandra_group](https://somerville.ed.ac.uk/project/stacks/stack/0fb3dcdd-6db6-4200-b511-5df63601906c/cassandra_group/).resources[0].resources.extra_vol_attachment: The request you have made requires authentication. (HTTP 401)
cassandra_group	e5cdfb6b-118b-416d-a06c-fe8042463134 	14 hours, 12 minutes 	Create Failed 	Unauthorized: resources.cassandra_group.resources[0].resources.extra_vol_attachment: The request you have made requires authentication. (HTTP 401)

**Comment by GregBlow** [comment]
There appear to be two component problems:

1) Flavours with ephemeral disk (kafka) fail to create
2) Flavours with additional block storage (cassandra and sherlock) fail to complete, at least under certain circumstances.

Ephemeral disk test template:
[basicHeat_disk_varieties.txt](https://github.com/lsst-uk/somerville-operations/files/10555072/basicHeat_disk_varieties.txt)

**Comment by GregBlow** [comment]
2023-02-01 08:43:58.144 21 INFO nova.scheduler.host_manager [req-7a96cbe7-1cec-48cd-9b88-fc246648d666 - - - - -] The instance sync for host 'sv-hpe-0-2' did not match. Re-created its InstanceList.

**Comment by GregBlow** [comment]
kafka and kafka-test flavours still work when deploying a single instance in horizon.

**Comment by GregBlow** [comment]
Michal has updated container images, however problem remains extant. Use of https://github.com/lsst-uk/somerville-operations/files/10555072/basicHeat_disk_varieties.txt fails, however setting kafka_flavor to 'small' rather than 'kafka_test' works.

**Comment by GregBlow** [comment]
```
      block_device_mapping_v2:
        - device_name: sda
          volume_id: { get_resource: vol }
          delete_on_termination: true
```

```
suggested to change to 

      block_device_mapping_v2:
        - boot_index: -1
          device_type: disk
          delete_on_termination: false
          device_name: /dev/vdb
          ephemeral_format: ext4
          ephemeral_size: 800
        - volume_id: { get_resource: vol }
          delete_on_termination: true
```

**Comment by gpfrancis** [comment]
Tried some tests - see https://ifaedinburghs-ofn4738.slack.com/archives/C01Q56Q78LT/p1676978420802669

Attempting to deploy the Lasair stack with just a single kafka instance gave the following error:
```
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "msg": "Failure in updating stack: Resource UPDATE failed: resources.kafka_group: Resource CREATE failed: BadRequest: resources[0].resources.srv: Block Device Mapping is Invalid: failed to get volume d72aea40-8e8d-4eb3-9603-4dbb3f4dbe29. (HTTP 400) (Request-ID: req-750f4014-9b55-4ff8-b795-30afd4bc605f)"}
```

This is essentially the same error as trying to deploy any instance of any flavour, with or without additional attached volumes, currently produces.

My conclusion is that I am currently unable to test whether the change fixes the kafka-specific part of the problem because the general problem of being unable to create any instances at all is blocking, while noting that even if this change fixes the problem for the kafka flavour it likely also breaks the template for every other flavour.

**Comment by GregBlow** [comment]
second (more complex) block device mapping:

```
block_device_mapping_v2:
        - boot_index: -1
          device_type: disk
          delete_on_termination: false
          device_name: /dev/vdb
          ephemeral_format: ext4
          ephemeral_size: 800  
		  volume_id: { get_resource: vol }
          delete_on_termination: true
```
